### ISSUE TITLE
Try to dockerize Deming

### ISSUE THREAD

**Issue by 0xlildoudou** [dbarzin/deming#18]
Hi,

I have try to dockerize Deming but i have an error when i run : php artisan migrate --seed
![image](https://github.com/dbarzin/deming/assets/67382584/97006bce-3f8c-40a8-9b05-1b49e41d9db8)

code link: https://github.com/0xlildoudou/deming/tree/dockerized

Thanks

**Comment by poooldo** [comment]
I cloned you repository, tested it and was able to reproduce.

**Comment by poooldo** [comment]
I cloned you repository and was able to reproduce. After some investigations, It seems that this table alteration fails on mysql 5.7 BUT if you change your image to 8.0 (in his tutorial, he uses ubuntu 22.04 which has a version 8), the problem disappears :

`# /opt/init.sh 

   INFO  Preparing database.  

  Creating migration table ............................................................................................................... 22ms DONE

   INFO  Running migrations.  

  2014_10_12_000000_create_users_table ................................................................................................... 48ms DONE
  2014_10_12_100000_create_password_resets_table ......................................................................................... 26ms DONE
  2016_06_01_000001_create_oauth_auth_codes_table ........................................................................................ 54ms DONE
  2016_06_01_000002_create_oauth_access_tokens_table ..................................................................................... 50ms DONE
  2016_06_01_000003_create_oauth_refresh_tokens_table .................................................................................... 64ms DONE
  2016_06_01_000004_create_oauth_clients_table ........................................................................................... 38ms DONE
  2016_06_01_000005_create_oauth_personal_access_clients_table ........................................................................... 10ms DONE
  2019_07_28_175941_create_domains_table ................................................................................................. 12ms DONE
  2019_08_09_084322_create_measures_table ................................................................................................ 44ms DONE
  2019_08_09_105245_create_controls_table ................................................................................................ 80ms DONE
  2019_12_14_000001_create_personal_access_tokens_table .................................................................................. 45ms DONE
  2020_04_12_073028_create_documents_table ............................................................................................... 43ms DONE
  2022_04_23_081110_add_next_control_id .................................................................................................. 50ms DONE
  2022_05_15_030940_control_score_to_int ................................................................................................. 34ms DONE
  2022_12_21_113730_add_user_language .................................................................................................... 11ms DONE
  2023_01_29_114100_add_tags ............................................................................................................. 48ms DONE
  2023_01_30_180336_normalization ........................................................................................................ 77ms DONE
  2023_03_09_222639_alter_attributes_values ............................................................................................... 5ms DONE
  2023_04_06_202034_alter_attribute_length ............................................................................................... 16ms DONE
  2023_04_19_112145_change_clause_type ................................................................................................... 28ms DONE
  2023_06_18_170340_owner ............................................................................................................... 196ms DONE

   INFO  Seeding database.  


   INFO  Application key set successfully.  


   INFO  The [public/storage] link has been connected to [storage/app/public].  

Remove all controls and documents
perPeriod=0
curDate=2022-07-01 15:44:57
delta=0
Lopp on measures
Done.

   INFO  Server running on [http://0.0.0.0:8000].  
`

Also, we have to change your init.sql a little bit because the create user function fails : It seems thaht you need to put localhost instead of %

**Comment by dbarzin** [comment]
I do not seen any "init.sql" file in the source code.

**Comment by dbarzin** [comment]
It is possible to make conditional tests in migration base on DB::getDriverName()

    if (DB::getDriverName() !== 'pgsql') {
        // code for PGSql
    } else {
        // code fo mySQL
    }

**Comment by 0xlildoudou** [comment]
Thanks for your quick feedback :)
I started with mysql:8 but went back to mysql:5.7 to try and get a different state.
I did some research after posting the issue and it could be the virtualisation environment.
I will test on a newer environment with your feedback. (thx @poooldo )

**Comment by 0xlildoudou** [comment]
![image](https://github.com/dbarzin/deming/assets/67382584/ee6c1134-e7f9-4a3e-9079-616cb8ce2d1f)
artisan migrate --seed done with more recent environment and with mysql:8

but when i connect on the web page i have this error
![image](https://github.com/dbarzin/deming/assets/67382584/9dd72867-a022-423e-90d9-fbd72d2510c3)

**Comment by yjacolin** [comment]
I add also a working Dockerfile, I don't know if you prepare a PR, do you?

**Comment by 0xlildoudou** [comment]
@dbarzin i have update the dockerfile:
```Dockerfile
WORKDIR /var/www/deming

RUN git clone https://www.github.com/dbarzin/deming .
RUN mkdir -p storage/framework/{views,cache,sessions} && mkdir -p bootstrap/cache
RUN chmod -R 775 /var/www/deming/storage && chown -R www-data:www-data /var/www/deming
```

@yjacolin can you share your work ? :)

**Comment by yjacolin** [comment]
To be honest, mine was for testing purpose, :) I didn't have started any docker-compose file.

https://github.com/yjacolin/deming/blob/dockerfile/Dockerfile

**Comment by poooldo** [comment]
@0xlildoudou I managed to make it work with nginx and mysql8 without using the init.sql

**Comment by 0xlildoudou** [comment]
Okay nice, that works for me.
Thanks for your work :)

**Comment by 0xlildoudou** [comment]
![image](https://github.com/dbarzin/deming/assets/67382584/27c91cc1-b578-4012-bf67-3994e9d4bbe5)

**Comment by poooldo** [comment]
Here is I want to put in a PR:

**Comment by yjacolin** [comment]
I think we can move docker stuff in a docker directory and remove my Dockerfile (I don't know why I pushed it, by mistake).

**Comment by poooldo** [comment]
@dbarzin 

Please can you review and merge this branch (this is the new one with reorganization):
https://github.com/poooldo/deming/tree/dockerize

I also updated the install documentation, In the next PR, I'm about to make available other databases.

**Comment by dbarzin** [comment]
Thanks, great job !

Have had to change the bootstrap file to make it run : 

        #/usr/bin/env bash
        
        command -v docker-compose
        if [ "$(echo $?)" != "0" ]; then
           curl -SL https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64 -o /tmp/docker-compose
           chmod +x /tmp/docker-compose && sudo cp /tmp/docker-compose /usr/local/bin/docker-compose
        fi
        
        docker-compose config > docker-compose.configured.yml
        
        docker-compose -f docker-compose.configured.yml up -d 
        

There is a better way to install docker-compose that does not require sudo :

https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-compose-on-ubuntu-22-04

**Comment by yjacolin** [comment]
@poooldo I think there is an issue with your deming repository as the main (dbarzin one) don't find you. That's mean you will have issue to create a PR of your changes. PR is easier to review changes.

**Comment by dbarzin** [comment]
I do not get it. What is the problem ? You have already submitted PR on this repo and I have been able to review changed before accepting it.

**Comment by 0xlildoudou** [comment]
Hi guys,

The best way to install docker compose it's : 
```shell
curl https://get.docker.com | sudo sh
```

The last release of Docker include docker compose (new version not use the dash between 'docker' and 'compose')

**Comment by dbarzin** [comment]
@poooldo Do you plan to change your PR ? Otherwise, I will accept it as it is and make changes based on comments above.
Thanks,
Didier
